name: Build Docker & Add Tag

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Target App Repository"
        required: true
        type: string
      version:
        description: "Version Tag (e.g., v1.0.0)"
        required: true
        type: string

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.repo_name }}
          token: ${{ secrets.GH_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="my-docker-repo/${{ inputs.repo_name }}:${{ inputs.version }}"
          docker build -t $IMAGE_NAME .

  add-tag:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Get Latest Commit SHA
        id: get_sha
        run: |
          LATEST_SHA=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ inputs.repo_name }}/git/ref/heads/main" \
            | jq -r '.object.sha')

          echo "sha=$LATEST_SHA" >> $GITHUB_ENV

      - name: Create Git Tag via API
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ inputs.repo_name }}/git/refs \
            -d "{\"ref\": \"refs/tags/${{ inputs.version }}\", \"sha\": \"${{ env.sha }}\"}"
